[package]
name = "pyo3-filelike"
version = "0.3.0"
edition = "2021"
description = "Rust access to Python file-like objects"
license = "Apache-2.0"
homepage = "https://github.com/jelmer/pyo3-filelike"

[dependencies]
pyo3 = ">=0.20.0"

[dev-dependencies]
pyo3 = { version = ">=0.20.0", features = ["auto-initialize"] }
