[package]
name = "pyo3-filelike"
version = "0.1.0"
edition = "2021"
description = "Rust access to Python file-like objects"
license = "Apache-2.0"

[dependencies]
pyo3 = ">=0.19.0"

[dev-dependencies]
pyo3 = { features = ["auto-initialize"] }
