on:
  push:
    tags:
      - 'v*'           # Push events to every tag not containing /
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
